// List<String> QuestionList =[
//   'assets/question/leval-1.png',
//   'assets/question/leval-2.png',
//   'assets/question/leval-3.png',
//   'assets/question/leval-4.png',
//   'assets/question/leval-5.png',
//   'assets/question/leval-6.png',
//   'assets/question/leval-7.png',
//   'assets/question/leval-8.png',
//   'assets/question/leval-9.png',
//   'assets/question/leval-10.png',
//   'assets/question/leval-11.png',
//   'assets/question/leval-12.png',
//   'assets/question/leval-13.png',
//   'assets/question/leval-14.png',
//   'assets/question/leval-15.png',
//   'assets/question/leval-16.png',
//   'assets/question/leval-17.png',
//   'assets/question/leval-18.png',
//   'assets/question/leval-19.png',
//   'assets/question/leval-20.png',
//   'assets/question/leval-21.png',
//   'assets/question/leval-22.png',
//   'assets/question/leval-23.png',
//   'assets/question/leval-24.png',
//   'assets/question/leval-25.png',
//   'assets/question/leval-26.png',
//   'assets/question/leval-27.png',
//   'assets/question/leval-28.png',
//   'assets/question/leval-29.png',
//   'assets/question/leval-30.png',
//   'assets/question/leval-31.png',
//   'assets/question/leval-32.png',
//   'assets/question/leval-33.png',
//   'assets/question/leval-34.png',
//   'assets/question/leval-35.png',
//   'assets/question/leval-36.png',
//   'assets/question/leval-37.png',
//   'assets/question/leval-38.png',
//   'assets/question/leval-39.png',
//   'assets/question/leval-40.png',
//   'assets/question/leval-41.png',
//   'assets/question/leval-42.png',
//   'assets/question/leval-43.png',
//   'assets/question/leval-44.png',
//   'assets/question/leval-45.png',
//   'assets/question/leval-46.png',
//   'assets/question/leval-47.png',
//   'assets/question/leval-48.png',
//   'assets/question/leval-49.png',
//   'assets/question/leval-50.png',
// ];

var questionList = [
  {'questionPath': 'assets/question/leval-1.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-2.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-3.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-4.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-5.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-6.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-7.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-8.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-9.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-10.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-11.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-12.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-13.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-14.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-15.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-16.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-17.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-18.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-19.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-20.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-21.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-22.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-23.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-24.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-25.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-26.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-27.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-28.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-29.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-30.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-31.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-32.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-33.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-34.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-35.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-36.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-37.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-38.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-39.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-40.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-41.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-44.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-45.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-46.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-47.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-48.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-49.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-50.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-51.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-52.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-53.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-54.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-55.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-56.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-57.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-58.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-59.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-60.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-61.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-62.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-63.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-64.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-65.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-66.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-67.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-68.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-69.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-70.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-71.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-72.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-73.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-74.png', 'ans': '111'},
  {'questionPath': 'assets/question/leval-75.png', 'ans': '111'},

];

// List<String> QuestionList = List.generate(75, (index) => 'assets/question/leval-${index+1}.png',);